config/routes.rb
Rails.application.routes.draw do

  ### i18対応の為のscop -- を入れたが為に追加(https://mikazuki.hatenablog.jp/entry/2016/01/16/041347)
  devise_for :users, skip: [:sign_up, :sign_in, :sign_out, :registrations, :sessions, :passwords, :confirmations, :unlock],
  controllers: { omniauth_callbacks: 'users/omniauth_callbacks' }

  devise_for :sellers, skip: [:sign_up, :sign_in, :sign_out, :registrations, :sessions, :passwords, :confirmations, :unlock]

  scope '(:locale)', locale: /#{I18n.available_locales.map(&:to_s).join('|')}/ do

  ###緊急避難###
  if Rails.env == "production"
    root 'corporate#top'
    get 'corporate' => 'corporate#top'

  elsif Rails.env == "development"

  #何故deviseが一番上に来るべきか https://teratail.com/questions/163615

  devise_for :users, skip:[:omniauth_callbacks], controllers: {
    # omniauth_callbacks: 'users/omniauth_callbacks',
    registrations:'users/registrations',
    sessions:'users/sessions'
  }

  devise_for :sellers, skip:[:omniauth_callbacks], controllers: {
    registrations:'sellers/registrations',
    sessions:'sellers/sessions'
  }

  root 'top#index'

  get 'mypage' => 'top#mypage'
  get 'bidded_items' => 'top#bidded_items'

  resources :sellers, only:[:index, :show] do
    get :coming, on: :member
    get :finished, on: :member
  end

  resources :tenders, only:[:index, :show] do
    resources :engines, only:[:show] do
      resources :bid_prices, only:[:new, :create, :edit, :update, :destroy]
    end
  end


  namespace :sellers, path:"organizer" do
    root 'top#index'
    resources :tenders do
      resources :engines
    end
    resource :tender_rule, only:[:show, :new, :create, :edit, :update]
    resources :tender_locations, only:[:new, :edit, :create, :update, :destroy]

    get 'account_info' => 'top#account_info'
    get 'new_seller_register_inquiry' => 'inquiry#new_seller_register_inquiry' # 販売企業入力画面
    post 'new_seller_register_inquiry_confirm' => 'inquiry#new_seller_register_inquiry_confirm' # 確認画面
    post 'new_seller_register_inquiry_thanks' => 'inquiry#new_seller_register_inquiry_thanks' # 送信完了画面
  end

  get 'corporate' => 'corporate#top'

end

end

end ###緊急避難

app/models/engine.rb
# == Schema Information
#
# Table name: engines
#
#  id                  :bigint(8)        not null, primary key
#  seller_id           :bigint(8)        not null
#  tender_id           :bigint(8)        not null
#  car_make            :string           not null
#  car_model           :string           not null
#  car_model_code      :string
#  registration_year   :date
#  condition           :integer          default(0), not null
#  engine_model_code   :string
#  mileage             :string
#  drive               :integer          default(0), not null
#  mission_type        :integer          default(0), not null
#  intake_manifold     :integer          default(0), not null
#  throttle_body       :integer          default(0), not null
#  exhaust_manifold    :integer          default(0), not null
#  ignition_coil       :integer          default(0)
#  turbo_charger       :integer          default(0)
#  fly_wheel           :integer          default(0), not null
#  compressor          :integer          default(0), not null
#  power_steering_pump :integer          default(0), not null
#  starter             :integer          default(0), not null
#  alternator          :integer          default(0), not null
#  ecu                 :integer          default(0), not null
#  engine_harness      :integer          default(0), not null
#  front_suspension    :integer          default(0), not null
#  rear_suspension     :integer          default(0), not null
#  remarks             :text
#  minimum_price       :integer          default(10000), not null
#  sold                :boolean          default(FALSE), not null
#  created_at          :datetime         not null
#  updated_at          :datetime         not null
#

class Engine < ApplicationRecord

  has_many :bid_prices, dependent: :destroy
  has_many :bidders, through: :bid_prices, source: :user

  belongs_to :tender
  belongs_to :seller

  validates :car_make, presence: true


  CARMAKE_OPTIONS = {
    "TOYOTA" => "トヨタ", "NISSAN" => "日産", "HONDA" => "ホンダ", "MAZDA" => "マツダ",
    "SUBARU" => "スバル", "MITSUBISHI" => "三菱", "ISUZU" => "イスズ", "HINO" => "日野",
    "SUZUKI" => "スズキ", "DAIHATSU" => "ダイハツ",
    "VOLKSWAGEN" => "フォルクスワーゲン", "BMW"=>"ビーエムダブリュー", "MERCEDESBENZ" => "メルセデスベンツ",
    "RENAULT" => "ルノー", "PEUGEOT" => "プジョー", "CITROEN" => "シトロエン",
    "FORD" => "フォード", "GM" => "ゼネラルモーター"
  }

end

app/controllers/engines_controller.rb
class EnginesController < ApplicationController
  def show
    engines = Engine.joins(:tender).where('preparation_status= ?', "1")
    @engine = engines.find(params[:id])
    @tender_rule = @engine.seller.tender_rule
    @bid_price = BidPrice.new
  end
end

app/controllers/sellers/engines_controller.rb
class Sellers::EnginesController < ApplicationController
  before_action :authenticate_seller!

  def index
  end

  def show
    @engine = Engine.find(params[:id])
    @this_tender = @engine.tender
    @bidders = @engine.bidders
  end

  def new
    @current_tender = Tender.find(params[:tender_id])
    @engine = Engine.new
  end

  def edit
  end

  def create
    current_tender = Tender.find(params[:tender_id])
    @engine = Engine.new(engine_params)
    @engine.tender = current_tender
    @engine.seller = current_seller
    if @engine.save
      flash.notice = "エンジンを登録しました。"
      redirect_to sellers_tender_path(current_tender)
    else
      render "new"
    end
  end

  def update
  end

  private def engine_params
    params.require(:engine).permit(
      :seller_id, :tender_id, :car_make, :car_model, :car_model_code,
      :registration_year, :condition, :engine_model_code,
      :mileage, :drive, :mission_type, :intake_manifold, :throttle_body,
      :exhaust_manifold, :ignition_coil, :turbo_charger, :fly_wheel,
      :compressor, :power_steering_pump, :starter, :alternator,
      :ecu, :engine_harness, :front_suspension, :rear_suspension,
      :remarks, :minimum_price, :sold
    )
  end

end

app/views/engines/_place_bid.html.erb
<div class="modal text-dark" id="place-bid-<%= engine.id %>", tabindex="-1" role="dialog">
  <div class="modal-dialog" role="document">
    <div class="modal-content">

      <div class="modal-header">
        <h5 class="modal-title">
          input your price for
          <span style="font-size:2rem;">
            <strong><%= engine.engine_model_code %></strong>
          </span>

        </h5>
        <button type="button" class="close" data-dismiss="modal" aria-label="Close">
          <span aria-hidden="true">&times;</span>
        </button>
      </div>

      <%= form_for @bid_price, url: tender_engine_bid_prices_path(@engine.tender, engine) do |f| %>

      <div class="modal-body">
        <div class="form-group">
          <%= f.text_field :price, class: 'form-control', required: true, placeholder:"input by JPY" %>
        </div>
      </div>

      <div class="modal-footer">

        <%= f.submit "Submit!", class:"btn btn-success" %>

        <button type="button" class="btn btn-outline-secondary" data-dismiss="modal">
          <i class="fas fa-times"></i>
          &nbsp;<strong>Reconsider</<strong>
          </button>
        </div>

        <% end %>

    </div>
  </div>
</div>

app/views/engines/show.html.erb
<div class="container-fluid bg-light">
  <div class="container">
    <div class="row">

      <div class="col-lg-4 col-12 my-3">

        <div id="wrap" class="p-1 mb-2 bg-light">
          <ul id="slider" class="pl-0">
            <li class="slide-item bg-dark">
              <%= image_tag("parts_example.JPG", alt: "parts_example")%>
            </li>
            <li class="slide-item bg-dark">
              <%= image_tag("parts_example_2.JPG", alt: "parts_example")%>
            </li>
            <li class="slide-item bg-dark">
              <%= image_tag("parts_example_3.JPG", alt: "parts_example")%>
            </li>
          </ul>

          <ul id="thumbnail_slider" class=" bg-secondary pl-0">
            <li class="thumbnail-item">
              <%= image_tag("parts_example.JPG", alt: "parts_example")%>
            </li>
            <li class="thumbnail-item">
              <%= image_tag("parts_example_2.JPG", alt: "parts_example")%>
            </li>
            <li class="thumbnail-item">
              <%= image_tag("parts_example_3.JPG", alt: "parts_example")%>
            </li>
          </ul>

        </div>


        <div class="alert alert-warning d-none d-lg-block">
          <i class="fas fa-exclamation-triangle"></i>
          <strong>Tender Rule</strong>

          <table class="table mt-3">
            <tbody>
              <tr>
                <th scope="row">
                  <small>8% Tax</small>
                </th>
                <td>
                  <small>
                  <% if @tender_rule.tax == 0 %>
                  Not Included - Pay Separately
                  <% elsif @tender_rule.tax == 1 %>
                  Included
                  <% end %>
                  </small>
                </td>
              </tr>
              <tr>
                <th scope="row">
                  <small>Payment</small>
                </th>
                <td>
                  <small>
                  <% if @tender_rule.payment_cash_in_advance %>
                  <span class="badge badge-warning">Cash</span>
                  <% end %>
                  <% if @tender_rule.payment_bank_transfer_in_advance %>
                  <span class="badge badge-warning">Bank Transfer</span>
                  <% end %>
                  <% if @tender_rule.payment_credit_card_in_advance %>
                  <span class="badge badge-warning">Credit Card</span>
                  <% end %>
                  </small>
                </td>
              </tr>
              <tr>
                <th scope="row">
                  <small>Delivery</small>
                </th>
                <td>
                  <small>
                  <% if @tender_rule.delivery == 0 %>
                  No
                  <% elsif @tender_rule.delivery == 1 %>
                  Yes - contact the comapany
                  <% end %>
                  </small>
                </td>
              </tr>
              <tr>
                <th scope="row">
                  <small>Pick Up</small>
                </th>
                <td>
                  <small>
                  within <%= @tender_rule.pickup_date %> days
                  </small>
                </td>
              </tr>
              <tr>
                <th scope="row">
                  <small>Priority</small>
                </th>
                <td>
                  <small>
                  <% if @tender_rule.priority == 0 %>
                  first bidder will be prioritized
                  <% else %>
                  ---
                  <% end %>
                  </small>
                </td>
              </tr>
            </tbody>
          </table>
        </div>

      </div>

      <div class="col-lg-8 col-12">

        <% if flash[:bid_price_error_messages] %>

        <div id="error_explanation" class="alert alert-danger mt-3">
          <ul class="mb-0">
            <% flash[:bid_price_error_messages].each do |message| %>
            <li><%= message %></li>
            <% end %>
          </ul>
        </div>

        <% end %>

        <% if @bid_price.errors.any? %>
        <div id="error_explanation" class="alert alert-danger">
          <ul>
            <% @bid_price.errors.full_messages.each do |message| %>
            <li><%= message %></li>
            <% end %>
          </ul>
        </div>
        <% end %>

        <div class="alert alert-success text-center my-3" role="alert">

          <h3 class="text-success mb-0">
            <span class="small">min price:</span>
            <strong>
              <%= number_to_currency(@engine.minimum_price, :unit => " JPY ", :precision => 0) %>
            </strong>
          </h3>

          <hr>

          <% if current_user && !current_user&.biddable_for?(@engine) %>

          <div class="alert alert-warning">
          You have already bidded at
          <% @yourprice = BidPrice.find_by(engine_id: @engine.id, user_id: current_user.id) %>
          <%= number_to_currency(@yourprice.price, :unit => " JPY ", :precision => 0) %>
          <br>
          <%= link_to "#", class:"btn btn-lg btn-success my-2" do %>
          Revise Your Bid
          <% end %>
          <br>
          <%= link_to "#", class:"text-secondary" do %>
          cancel your bid
          <% end %>
          </div>


          <% else %>

          <%= render "place_bid", engine: @engine %>
          <%= link_to "#place-bid-#{@engine.id}", data: {toggle: "modal"}, class:"btn btn-lg btn-success my-2" do%>
          <strong>Place Your Bid</strong>
          <% end %>

          <% end %>

          <br>

          <i class="fas fa-users"></i>
          <strong>
          <%= @engine.bidders.count %>
          </strong>
          bidders already
          <div class>
            <br>
            <i class="far fa-clock"></i>
            remaining
            <span class="text-danger"><strong>
            <%= @engine.tender.remaining_days %> <small>days</small>
            <%= @engine.tender.remaining_hours %> <small>hours</small>
            <%= @engine.tender.remaining_minutes %> <small>minutes</small>
            </strong></span>
          </div>

        <hr>

        This tender will be closed at
        <strong><span class="text-danger"><%= @engine.tender.ends_at.strftime("%d %b %Y (%a) %H:%M") %></span></strong>
        <br>
        check the other engines in this <%= link_to "tender", tender_path(@engine.tender) %>

        </div>

        <h3 class="mt-3 text-secondary"><strong>Specifications</strong></h3>
        <table class="table table-striped">
          <tbody>
            <tr>
              <th scope="row">Condition</th>
              <td>
                <% if @engine.condition == 0 %>
                Used
                <% elsif @engine.condition == 1 %>
                New - Genuine
                <% elsif @engine.condition == 2 %>
                new - Reman
                <% end %>
              </td>
            </tr>
            <tr>
              <th scope="row">Make</th>
              <td><%= @engine.car_make %></td>
            </tr>
            <tr>
              <th scope="row">Model</th>
              <td><%= @engine.car_model %></td>
            </tr>
              <th scope="row">Model Code</th>
              <td><%= @engine.engine_model_code %></td>
            </tr>
            <tr>
              <th scope="row">Reg. Year</th>
              <td><%= @engine.registration_year.strftime("%Y") %></td>
            </tr>
            <tr>
              <th scope="row">Drive</th>
              <td>
              <% if @engine.drive == 0 %>
              N/A
              <% elsif @engine.drive == 1 %>
              2WD
              <% elsif @engine.drive == 2 %>
              4WD
              <% end %>
              </td>
            </tr>
            <tr>
              <th scope="row">Mileage</th>
              <td><%= number_with_delimiter(@engine.mileage) %> &nbsp;km</td>
            </tr>
            <tr>
              <th scope="row">Engine Model Code</th>
              <td><%= @engine.engine_model_code %></td>
            </tr>
            <tr>
              <th scope="row">Drive</th>
              <td>
              <% if @engine.drive == 0 %>
              2WD(FF)
              <% elsif @engine.drive == 1 %>
              2WD(FR)
              <% elsif @engine.drive == 2 %>
              MR
              <% elsif @engine.drive == 3 %>
              RR
              <% elsif @engine.drive == 4 %>
              4WD
              <% end %>
              </td>
            </tr>
            <tr>
              <th scope="row">Mission</th>
              <td>
              <% if @engine.mission_type == 0 %>
              N/A
              <% elsif @engine.mission_type == 1 %>
              AT
              <% elsif @engine.mission_type == 2 %>
              MT
              <% elsif @engine.mission_type == 3 %>
              CVT
              <% end %>
              </td>
            </tr>
            <tr>
              <th scope="row">with</th>
              <td>
                <% if @engine.starter == 0 %>
                <span class="badge badge-success">Starter</span>
                <% end %>
                <% if @engine.alternator == 0 %>
                <span class="badge badge-success">Alternator</span>
                <% end %>
                <% if @engine.compressor == 0 %>
                <span class="badge badge-success">Compressor</span>
                <% end %>
                <% if @engine.power_steering_pump == 0 %>
                <span class="badge badge-success">Power Steering Pump</span>
                <% end %>
                <% if @engine.engine_harness == 0 %>
                <span class="badge badge-success">Engine Harness</span>
                <% end %>
                <% if @engine.ecu == 0 %>
                <span class="badge badge-success">ECU</span>
                <% end %>
                <% if @engine.front_suspension == 0 %>
                <span class="badge badge-success">Front Suspension</span>
                <% end %>
                <% if @engine.rear_suspension == 0 %>
                <span class="badge badge-success">Rear Suspension</span>
                <% end %>
              </td>
            </tr>
            <tr>
              <th scope="row">Remarks</th>
              <td>
                <% if @engine.remarks.present? %>
                <% @engine.remarks %>
                <% else %>
                ---
                <% end %>
              </td>
            </tr>

          </tbody>
        </table>
      </div>

    </div>
  </div>
</div>