config/routes.rb
Rails.application.routes.draw do

  ### i18対応の為のscop -- を入れたが為に追加(https://mikazuki.hatenablog.jp/entry/2016/01/16/041347)
  devise_for :users, skip: [:sign_up, :sign_in, :sign_out, :registrations, :sessions, :passwords, :confirmations, :unlock],
  controllers: { omniauth_callbacks: 'users/omniauth_callbacks' }

  devise_for :sellers, skip: [:sign_up, :sign_in, :sign_out, :registrations, :sessions, :passwords, :confirmations, :unlock]

  scope '(:locale)', locale: /#{I18n.available_locales.map(&:to_s).join('|')}/ do

  ###緊急避難###
  if Rails.env == "production"
    root 'corporate#top'
    get 'corporate' => 'corporate#top'

  elsif Rails.env == "development"

  #何故deviseが一番上に来るべきか https://teratail.com/questions/163615

  devise_for :users, skip:[:omniauth_callbacks], controllers: {
    # omniauth_callbacks: 'users/omniauth_callbacks',
    registrations:'users/registrations',
    sessions:'users/sessions'
  }

  devise_for :sellers, skip:[:omniauth_callbacks], controllers: {
    registrations:'sellers/registrations',
    sessions:'sellers/sessions'
  }

  root 'top#index'

  get 'mypage' => 'top#mypage'
  get 'bidded_items' => 'top#bidded_items'

  resources :sellers, only:[:index, :show] do
    get :coming, on: :member
    get :finished, on: :member
  end

  resources :tenders, only:[:index, :show] do
    resources :engines, only:[:show] do
      resources :bid_prices, only:[:new, :create, :edit, :update, :destroy]
    end
  end


  namespace :sellers, path:"organizer" do
    root 'top#index'
    resources :tenders do
      resources :engines
    end
    resource :tender_rule, only:[:show, :new, :create, :edit, :update]
    resources :tender_locations, only:[:new, :edit, :create, :update, :destroy]

    get 'account_info' => 'top#account_info'
    get 'new_seller_register_inquiry' => 'inquiry#new_seller_register_inquiry' # 販売企業入力画面
    post 'new_seller_register_inquiry_confirm' => 'inquiry#new_seller_register_inquiry_confirm' # 確認画面
    post 'new_seller_register_inquiry_thanks' => 'inquiry#new_seller_register_inquiry_thanks' # 送信完了画面
  end

  get 'corporate' => 'corporate#top'

end

end

end ###緊急避難

app/models/seller.rb
# == Schema Information
#
# Table name: sellers
#
#  id                     :bigint(8)        not null, primary key
#  company_name           :string
#  company_name_en        :string
#  company_address        :string
#  company_address_en     :string
#  company_url            :string
#  company_tell           :string
#  email                  :string           default(""), not null
#  encrypted_password     :string           default(""), not null
#  reset_password_token   :string
#  reset_password_sent_at :datetime
#  remember_created_at    :datetime
#  sign_in_count          :integer          default(0), not null
#  current_sign_in_at     :datetime
#  last_sign_in_at        :datetime
#  current_sign_in_ip     :inet
#  last_sign_in_ip        :inet
#  failed_attempts        :integer          default(0), not null
#  unlock_token           :string
#  locked_at              :datetime
#  created_at             :datetime         not null
#  updated_at             :datetime         not null
#

class Seller < ApplicationRecord
  has_many :tenders
  has_many :tender_locations
  has_many :engines
  has_many :autoparts
  has_one :tender_rule


  # Include default devise modules. Others available are:
  # :confirmable, :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable,
         :lockable, :timeoutable, :trackable
end

app/models/tender_rule.rb
# == Schema Information
#
# Table name: tender_rules
#
#  id                               :bigint(8)        not null, primary key
#  seller_id                        :bigint(8)        not null
#  payment_cash_in_advance          :boolean          not null
#  payment_bank_transfer_in_advance :boolean          not null
#  payment_credit_card_in_advance   :boolean          not null
#  tax                              :integer          default(0), not null
#  delivery                         :integer          default(0), not null
#  pickup_date                      :integer          not null
#  cancel                           :integer          default(0), not null
#  priority                         :integer          default(0), not null
#  disclose                         :integer          default(0), not null
#  created_at                       :datetime         not null
#  updated_at                       :datetime         not null
#

class TenderRule < ApplicationRecord
  belongs_to :seller, dependent: :destroy
end

app/controllers/sellers/confirmations_controller.rb
# frozen_string_literal: true

class Sellers::ConfirmationsController < Devise::ConfirmationsController
  # GET /resource/confirmation/new
  # def new
  #   super
  # end

  # POST /resource/confirmation
  # def create
  #   super
  # end

  # GET /resource/confirmation?confirmation_token=abcdef
  # def show
  #   super
  # end

  # protected

  # The path used after resending confirmation instructions.
  # def after_resending_confirmation_instructions_path_for(resource_name)
  #   super(resource_name)
  # end

  # The path used after confirmation.
  # def after_confirmation_path_for(resource_name, resource)
  #   super(resource_name, resource)
  # end
end

app/controllers/sellers/engines_controller.rb
class Sellers::EnginesController < ApplicationController
  before_action :authenticate_seller!

  def index
  end

  def show
    @engine = Engine.find(params[:id])
    @this_tender = @engine.tender
    @bidders = @engine.bidders
  end

  def new
    @current_tender = Tender.find(params[:tender_id])
    @engine = Engine.new
  end

  def edit
  end

  def create
    current_tender = Tender.find(params[:tender_id])
    @engine = Engine.new(engine_params)
    @engine.tender = current_tender
    @engine.seller = current_seller
    if @engine.save
      flash.notice = "エンジンを登録しました。"
      redirect_to sellers_tender_path(current_tender)
    else
      render "new"
    end
  end

  def update
  end

  private def engine_params
    params.require(:engine).permit(
      :seller_id, :tender_id, :car_make, :car_model, :car_model_code,
      :registration_year, :condition, :engine_model_code,
      :mileage, :drive, :mission_type, :intake_manifold, :throttle_body,
      :exhaust_manifold, :ignition_coil, :turbo_charger, :fly_wheel,
      :compressor, :power_steering_pump, :starter, :alternator,
      :ecu, :engine_harness, :front_suspension, :rear_suspension,
      :remarks, :minimum_price, :sold
    )
  end

end

app/controllers/sellers/inquiry_controller.rb
class Sellers::InquiryController < ApplicationController
  def new_seller_register_inquiry
    @new_seller_register_inquiry = Inquiry.new
  end

  def new_seller_register_inquiry_confirm
    @inquiry = Inquiry.new(reqister_params)
    if @inquiry.valid?
      render action: 'new_seller_register_inquiry_confirm'
    else
      render action: 'new_seller_register_inquiry'
    end
  end

  def new_seller_register_thanks
    if params[:commit]
      # メール送信
      @inquiry = Inquiry.new(params[:inquiry])
      InquiryMailer.received_email(@inquiry).deliver
      # 完了画面を表示
      render :action => 'new_seller_register_thanks'
    else
      render action 'new_seller_register_inquiry'
    end
  end

  def reqister_params
    params.require(:inquiry).permit(
      :company_name, :company_tell, :company_url, :email, :email_confirmation, :contents
    )
  end
end

app/controllers/sellers/omniauth_callbacks_controller.rb
# frozen_string_literal: true

class Sellers::OmniauthCallbacksController < Devise::OmniauthCallbacksController
  # You should configure your model like this:
  # devise :omniauthable, omniauth_providers: [:twitter]

  # You should also create an action method in this controller like this:
  # def twitter
  # end

  # More info at:
  # https://github.com/plataformatec/devise#omniauth

  # GET|POST /resource/auth/twitter
  # def passthru
  #   super
  # end

  # GET|POST /users/auth/twitter/callback
  # def failure
  #   super
  # end

  # protected

  # The path used when OmniAuth fails
  # def after_omniauth_failure_path_for(scope)
  #   super(scope)
  # end
end

app/controllers/sellers/passwords_controller.rb
# frozen_string_literal: true

class Sellers::PasswordsController < Devise::PasswordsController
  # GET /resource/password/new
  # def new
  #   super
  # end

  # POST /resource/password
  # def create
  #   super
  # end

  # GET /resource/password/edit?reset_password_token=abcdef
  # def edit
  #   super
  # end

  # PUT /resource/password
  # def update
  #   super
  # end

  # protected

  # def after_resetting_password_path_for(resource)
  #   super(resource)
  # end

  # The path used after sending reset password instructions
  # def after_sending_reset_password_instructions_path_for(resource_name)
  #   super(resource_name)
  # end
end

app/controllers/sellers/registrations_controller.rb
# frozen_string_literal: true

class Sellers::RegistrationsController < Devise::RegistrationsController
  before_action :configure_sign_up_params, only: [:create]
  before_action :configure_account_update_params, only: [:update]

  # GET /resource/sign_up
  # def new
  #   super
  # end

  # POST /resource
  # def create
  #   super
  # end

  # GET /resource/edit
  # def edit
  #   super
  # end

  # PUT /resource
  # def update
  #   super
  # end

  # DELETE /resource
  # def destroy
  #   super
  # end

  # GET /resource/cancel
  # Forces the session data which is usually expired after sign
  # in to be expired now. This is useful if the user wants to
  # cancel oauth signing in/up in the middle of the process,
  # removing all OAuth session data.
  # def cancel
  #   super
  # end

  protected

  # If you have extra params to permit, append them to the sanitizer.
  def configure_sign_up_params
    devise_parameter_sanitizer.permit(:sign_up, keys: [:company_name, :company_name_en, :company_address, :company_address_en, :company_url, :company_tell])
  end

  # If you have extra params to permit, append them to the sanitizer.
  def configure_account_update_params
    devise_parameter_sanitizer.permit(:account_update, keys: [:company_name, :company_name_en, :company_address, :company_address_en, :company_url, :company_tell])
  end

  def after_update_path_for(resource)
    sellers_account_info_path
  end


  # The path used after sign up.
  # def after_sign_up_path_for(resource)
  #   super(resource)
  # end

  # The path used after sign up for inactive accounts.
  # def after_inactive_sign_up_path_for(resource)
  #   super(resource)
  # end
end

app/controllers/sellers/sessions_controller.rb
# frozen_string_literal: true

class Sellers::SessionsController < Devise::SessionsController
  # before_action :configure_sign_in_params, only: [:create]

  # GET /resource/sign_in
  # def new
  #   super
  # end

  # POST /resource/sign_in
  # def create
  #   super
  # end

  # DELETE /resource/sign_out
  # def destroy
  #   super
  # end

  # protected

  # If you have extra params to permit, append them to the sanitizer.
  # def configure_sign_in_params
  #   devise_parameter_sanitizer.permit(:sign_in, keys: [:attribute])
  # end
end

app/controllers/sellers/tender_locations_controller.rb
class Sellers::TenderLocationsController < ApplicationController

  before_action :authenticate_seller!

  def new
    @tender_location = TenderLocation.new
  end

  def edit
    @tender_location = TenderLocation.find(params[:id])
  end

  def create
    @tender_location = TenderLocation.new(tender_location_params)
    @tender_location.address_country_part = "Japan"
    @tender_location.seller = current_seller
    if @tender_location.save
      flash.notice = "入札開催場所を追加しました。"
      redirect_to sellers_tender_rule_path
    else
      render "new"
    end
  end

  def update
    @tender_location = TenderLocation.find(params[:id])
    @tender_location.assign_attributes(tender_location_params)
    if @tender_location.save
      redirect_to sellers_tender_rule_path, notice: "入札開催場所をupdateしました。"
    else
      render "edit"
    end
  end

  def destroy
    @tender_location = TenderLocation.find(params[:id])
    @tender_location.destroy!

    redirect_to sellers_tender_rule_path, alert: "削除しました。"
  end

  private def tender_location_params
    params.require(:tender_location).permit(
      :seller_id, :address, :address_country_part,
      :address_prefecture_part, :address_city_part, :address_rest_part
    )
  end

end

app/controllers/sellers/tender_rules_controller.rb
class Sellers::TenderRulesController < ApplicationController

  before_action :authenticate_seller!

  def show
    @tender_locations = current_seller.tender_locations
    @tender_rule = current_seller.tender_rule
  end

  def new
    @tender_rule = TenderRule.new
  end

  def create
    @tender_rule = TenderRule.new(tender_rule_params)
    @tender_rule.seller = current_seller
    if @tender_rule.save
      flash.notice = "入札会ルールを設定しました。"
      redirect_to sellers_tender_rule_path
    else
      render "new"
    end
  end

  def edit
    @tender_rule = current_seller.tender_rule
  end

  def update
    @tender_rule = current_seller.tender_rule
    @tender_rule.assign_attributes(tender_rule_params)
    if @tender_rule.save
      flash.notice = "入札会ルールをupdateしました。"
      redirect_to sellers_tender_rule_path
    else
      render "edit"
    end
  end

  private def tender_rule_params
    params.require(:tender_rule).permit(
      :seller_id, :payment_cash_in_advance, :payment_bank_transfer_in_advance,
      :payment_credit_card_in_advance, :tax, :delivery,
      :pickup_date, :cancel, :priority, :disclose
    )
  end

end

app/controllers/sellers/tenders_controller.rb
class Sellers::TendersController < ApplicationController

  before_action :authenticate_seller!

  def index
    @tenders = current_seller.tenders.order(id: :desc)
  end

  def show
    @tender = Tender.find(params[:id])
    @engines = @tender.engines
  end

  def new
    @tender = Tender.new
    time0 = Time.current.beginning_of_day
    @tender.starts_at = time0.advance(days: 1, hours: 9)
    @tender.ends_at = time0.advance(days: 3, hours: 12)
    @tender_location_candidates = current_seller.tender_locations
  end

  def edit
    @tender = Tender.find(params[:id])
    @tender_location_candidates = current_seller.tender_locations
  end

  def create
    @tender = Tender.new(tender_params)
    @tender.seller = current_seller
    if @tender.valid?
      @tender.save!
      flash.notice = "入札会を設定しました。掲載商品を追加してください。"
      redirect_to sellers_tender_path(@tender)
    else
      @tender_location_candidates = current_seller.tender_locations
      render "new"
    end
  end

  def update
    @tender = Tender.find(params[:id])
    @tender.assign_attributes(tender_params)
    if @tender.save
      flash.alert = "入札会の設定をupdateしました。"
      redirect_to sellers_tender_path(@tender)
    else
      @tender_location_candidates = current_seller.tender_locations
      render "edit"
    end
  end

  def destroy
    @tender = Tender.find(params[:id])
    @tender.destroy!

    redirect_to :sellers_tenders, alert: "入札会を削除しました。"
  end

  private def tender_params
    params[:tender].permit(
      :seller_id, :tender_location_id,
      :starts_at_date_part, :starts_at_time_part,
      :ends_at_date_part, :ends_at_time_part,
      :status
    )
  end

end

app/controllers/sellers/top_controller.rb
class Sellers::TopController < ApplicationController
  before_action :authenticate_seller!, only:[:index, :account_info]

  def index
  end

  def account_info
    @seller = current_seller
  end

end

app/controllers/sellers/unlocks_controller.rb
# frozen_string_literal: true

class Sellers::UnlocksController < Devise::UnlocksController
  # GET /resource/unlock/new
  # def new
  #   super
  # end

  # POST /resource/unlock
  # def create
  #   super
  # end

  # GET /resource/unlock?unlock_token=abcdef
  # def show
  #   super
  # end

  # protected

  # The path used after sending unlock password instructions
  # def after_sending_unlock_instructions_path_for(resource)
  #   super(resource)
  # end

  # The path used after unlocking the resource
  # def after_unlock_path_for(resource)
  #   super(resource)
  # end
end

app/controllers/sellers_controller.rb
class SellersController < ApplicationController

  def index
  end

  def show
    @seller = Seller.find(params[:id])
    @tender_rule = @seller.tender_rule
    @tenders = @seller.tenders.ongoing.order(:starts_at)
  end

  # GET (member)
  def coming
    @seller = Seller.find(params[:id])
    @tender_rule = @seller.tender_rule
    @tenders = @seller.tenders.coming.order(:starts_at)
    render action: :show
  end

  # GET (member)
  def finished
    @seller = Seller.find(params[:id])
    @tender_rule = @seller.tender_rule
    @tenders = @seller.tenders.finished.order(:starts_at)
    render action: :show
  end

end

app/views/sellers/tender_rules/_delete_confirmation.html.erb
<div class="modal text-dark" id="delete-confirmation-<%= location.id %>", tabindex="-1" role="dialog">
  <div class="modal-dialog" role="document">
    <div class="modal-content">
      <div class="modal-header">
        <h5 class="modal-title">以下の住所を削除します</h5>
        <button type="button" class="close" data-dismiss="modal" aria-label="Close">
          <span aria-hidden="true">&times;</span>
        </button>
      </div>
      <div class="modal-body">
        <span style="font-size:2rem;">
          <strong><%= location.address %></strong>
        </span>
      </div>
      <div class="modal-footer">
        <button type="button" class="btn btn-outline-secondary" data-dismiss="modal">
          <i class="fas fa-times"></i>
          &nbsp;<strong>キャンセル</<strong>
        </button>
        <%= link_to sellers_tender_location_path(location), method: :delete, class:"btn btn-outline-danger" do%>
        <i class="far fa-trash-alt"></i>
        &nbsp;<strong>削除する</strong>
        <% end %>

      </div>
    </div>
  </div>
</div>

app/views/sellers/tender_rules/_form.html.erb
<div class="mt-5">
  <table class="table table-striped" style="border: 2px red solid;">
    <tbody>
      <tr>
        <th rowspan="3" class="bg-white">
          支払方法
          <br>
          <span class="text-danger">
            <small>
              可能な支払方法に
              <br>
              チェックを入れてください。
              <br>
              *複数選択可能
            </small>
          </span>
        </th>
        <td class="bg-white">
          <div class="form-group mb-0">
            <label class="custom-control custom-checkbox mb-0">
              <%= form.check_box :payment_cash_in_advance, class:"custom-control-input", checked:true %>
              <span class="custom-control-indicator"></span>
              <span class="custom-control-label">現金手渡（商品引取時）</span>
            </label>
          </div>
        </td>
      </tr>
      <tr>
        <td class="bg-white">
          <div class="form-group mb-0">
            <label class="custom-control custom-checkbox mb-0">
              <%= form.check_box :payment_bank_transfer_in_advance, class:"custom-control-input", checked:true %>
              <span class="custom-control-indicator"></span>
              <span class="custom-control-label">銀行振込（商品引取前）</span>
            </label>
          </div>
        </td>
      </tr>
      <tr>
        <td class="bg-white">
          <div class="form-group mb-0">
            <label class="custom-control custom-checkbox mb-0">
              <%= form.check_box :payment_credit_card_in_advance, class:"custom-control-input", checked:true %>
              <span class="custom-control-indicator"></span>
              <span class="custom-control-label">クレジットカード（商品引取前）</span>
            </label>
          </div>
        </td>
      </tr>
    </tbody>
  </table>
</div>




  <table class="table table-striped mt-5">
    <tbody>
      <tr>
        <th scope="row">消費税（8%）</th>
        <td>
          <%= form.radio_button :tax, 0 %>
          <%= form.label :tax_0, "別途支払い" %>
          &nbsp;&nbsp;&nbsp;
          <%= form.radio_button :tax, 1 %>
          <%= form.label :tax_1, "込み" %>
          &nbsp;&nbsp;&nbsp;
          <span class="text-danger">
            <small>
            *基本的に消費税は別途支払いとしてください。
            </small>
          </span>
        </td>
      </tr>
      <tr>
        <th scope="row">商品配送</th>
        <td>
          <%= form.radio_button :delivery, 0 %>
          <%= form.label :delivery_0, "不可" %>
          &nbsp;&nbsp;&nbsp;
          <%= form.radio_button :delivery, 1 %>
          <%= form.label :delivery_1, "可能（費用買主負担）" %>
        </td>
      </tr>
      <tr>
        <th scope="row">
          引取期限
          <br>
          <small>落札後●日以内</small>
        </th>
        <td>
          <div class="form-group">
            <%= select_tag :pickup_date, options_for_select((1..10).to_a), class:"form-control" %>
          </div>
        </td>
      </tr>
      <tr>
        <th scope="row">落札後キャンセル</th>
        <td>
          <%= form.radio_button :cancel, 0 %>
          <%= form.label :cancel_0, "不可" %>
        </td>
      </tr>
      <tr>
        <th scope="row">同額入札者がいる場合</th>
        <td>
          <%= form.radio_button :priority, 0 %>
          <%= form.label :priority_0, "先に入札した人優先" %>
        </td>
      </tr>
      <tr>
        <th scope="row">落札価格開示</th>
        <td>
          <%= form.radio_button :disclose, 0 %>
          <%= form.label :disclose_0, "開示" %>
          &nbsp;&nbsp;&nbsp;
          <%= form.radio_button :disclose, 1 %>
          <%= form.label :disclose_1, "非開示" %>
        </td>
      </tr>
    </tbody>
  </table>

app/views/sellers/tender_rules/edit.html.erb
<div class="container-fluid">
  <div class="row">

    <nav class="col-2 p-0 sidebar">
      <%= render 'sellers/shared/sidebar' %>
    </nav>

    <main class="col-10 ml-sm-auto">

      <div class="row">
        <div class="col-12">

          <h1 class="text-secondary my-4">
            <i class="fas fa-clipboard-list"></i>
            &nbsp;入札会ルール変更
          </h1>

          <%= form_for @tender_rule, url: :sellers_tender_rule do |form| %>
          <%= render 'sellers/tender_rules/form', form: form %>
          <%= form.submit "変更する", class:"btn btn-warning my-3" do %>
          <% end %>

          <%= link_to sellers_tender_rule_path, class:"btn btn-outline-dark ml-2" do %>
          <i class="fas fa-times"></i> キャンセル
          <% end %>

          <% end %>

        </div>
      </div>

    </main>

  </div>
</div>

app/views/sellers/tender_rules/new.html.erb
<div class="container-fluid">
  <div class="row">

    <nav class="col-2 p-0 sidebar">
      <%= render 'sellers/shared/sidebar' %>
    </nav>

    <main class="col-10 ml-sm-auto">

      <div class="row">
        <div class="col-12">

          <h1 class="text-secondary my-4">
            <i class="fas fa-clipboard-list"></i>
            &nbsp;入札会ルール設定
          </h1>

          <%= form_for @tender_rule, url: :sellers_tender_rule do |form| %>
          <%= render 'sellers/tender_rules/form', form: form %>
          <%= form.submit "設定する", class:"btn btn-warning my-3" do %>
          <% end %>

          <%= link_to sellers_tender_rule_path, class:"btn btn-outline-dark ml-2" do %>
          <i class="fas fa-times"></i> キャンセル
          <% end %>

          <% end %>

        </div>
      </div>

    </main>

  </div>
</div>

app/views/sellers/tender_rules/show.html.erb
<div class="container-fluid">
  <div class="row">

    <nav class="col-2 p-0 sidebar">
      <%= render 'sellers/shared/sidebar' %>
    </nav>

    <main class="col-10">

      <h1 class="text-secondary my-4">入札基本設定</h1>

      <ul class="ul-orange">
        <li>
          <h2 class="m-0 text-secondary">
            入札場所
          </h2>
        </li>
      </ul>

      <div class="alert alert-warning my-3" role="alert">
        現在
        <strong><span class="text-danger" style="font-size:2rem;">
          <%= @tender_locations.count %>
        </span></strong>
        箇所が登録されています。

        <%= link_to new_sellers_tender_location_path, class:"btn btn-warning" do %>
        <i class="fas fa-plus"></i>
        追加する
        <% end %>
      </div>

      <ol>
        <% @tender_locations.each do |location| %>

        <div class="mb-5">
        <h3>
          <li class="my-3 text-secondary">
            <%= location.address %>
          </li>
        </h3>
        <%= link_to edit_sellers_tender_location_path(location), class:"btn btn-sm btn-outline-dark" do %>
        <i class="far fa-edit"></i>
        変更
        <% end %>

        <%= render "delete_confirmation", location: location %>
        <%= link_to "#delete-confirmation-#{location.id}", data: {toggle: "modal"}, class:"btn btn-sm btn-outline-dark" do%>
        <i class="far fa-trash-alt"></i>
        削除
        <% end %>
        </div>

        <% end %>
      </ol>

      <ul class="ul-orange">
        <li>
          <h2 class="m-0 text-secondary">
            入札ルール
          </h2>
        </li>
      </ul>

      <% if @tender_rule %>

        <table class="table table-bordered table-striped mt-5">
          <tbody>
            <tr>
              <th>
                支払方法
              </th>
              <td>
                <% if @tender_rule.payment_cash_in_advance %>
                <span class="badge badge-warning" style="font-size:1rem;">
                  現金手渡（商品引取前）
                </span>
                <% end %>
                <% if @tender_rule.payment_bank_transfer_in_advance %>
                <span class="badge badge-warning" style="font-size:1rem;">
                  銀行振込（商品引取前）
                </span>
                <% end %>
                <% if @tender_rule.payment_credit_card_in_advance %>
                <span class="badge badge-warning" style="font-size:1rem;">
                  クレジットカード（商品引取前）
                </span>
                <% end %>
              </td>
            </tr>
            <tr>
              <th scope="row">消費税（8%）</th>
              <td>
                <% if @tender_rule.tax == 0 %>
                別
                <% elsif @tender_rule.tax == 1 %>
                税込み
                <% end %>
              </td>
            </tr>
            <tr>
              <th scope="row">商品配送</th>
              <td>
                <% if @tender_rule.delivery == 0 %>
                不可
                <% elsif @tender_rule.delivery == 1 %>
                可能（費用買主負担）
                <% end %>
              </td>
            </tr>
            <tr>
              <th scope="row">
                引取期限
              </th>
              <td>
                <div class="form-group">
                  落札後
                  <%= @tender_rule.pickup_date %>
                  日以内
                </div>
              </td>
            </tr>
            <tr>
              <th scope="row">落札後キャンセル</th>
              <td>
                <% if @tender_rule.cancel == 0 %>
                不可
                <% end %>
              </td>
            </tr>
            <tr>
              <th scope="row">同額入札者がいる場合</th>
              <td>
                <% if @tender_rule.priority == 0 %>
                先に入札した人を優先する
                <% elsif @tender_rule.priority == 1 %>
                その他
                <% end %>
              </td>
            </tr>
            <tr>
              <th scope="row">落札価格開示</th>
              <td>
                <% if @tender_rule.disclose == 0 %>
                開示
                <% elsif @tender_rule.disclose == 1 %>
                非開示
                <% end %>
              </td>
            </tr>
          </tbody>
        </table>

      <%= link_to edit_sellers_tender_rule_path, class:"btn btn-warning my-3" do %>
      <i class="far fa-edit"></i>
      入札ルールを変更する
      <% end %>

      <% else %>

      <div class="alert alert-danger my-5" role="alert">

        <p>
          <i class="fas fa-exclamation-triangle"></i>
          入札会ルールの設定をしてください。
        </p>


        <%= link_to new_sellers_tender_rule_path, class:"btn btn-danger" do %>
        <i class="fas fa-plus"></i>
        設定する
        <% end %>
      </div>

      <% end %>


    </main>
  </div>
</div>