config/routes.rb
Rails.application.routes.draw do

  ### i18対応の為のscop -- を入れたが為に追加(https://mikazuki.hatenablog.jp/entry/2016/01/16/041347)
  devise_for :users, skip: [:sign_up, :sign_in, :sign_out, :registrations, :sessions, :passwords, :confirmations, :unlock],
  controllers: { omniauth_callbacks: 'users/omniauth_callbacks' }

  devise_for :sellers, skip: [:sign_up, :sign_in, :sign_out, :registrations, :sessions, :passwords, :confirmations, :unlock]

  scope '(:locale)', locale: /#{I18n.available_locales.map(&:to_s).join('|')}/ do

  ###緊急避難###
  if Rails.env == "production"
    root 'corporate#top'
    get 'corporate' => 'corporate#top'

  elsif Rails.env == "development"

  #何故deviseが一番上に来るべきか https://teratail.com/questions/163615

  devise_for :users, skip:[:omniauth_callbacks], controllers: {
    # omniauth_callbacks: 'users/omniauth_callbacks',
    registrations:'users/registrations',
    sessions:'users/sessions'
  }

  devise_for :sellers, skip:[:omniauth_callbacks], controllers: {
    registrations:'sellers/registrations',
    sessions:'sellers/sessions'
  }

  root 'top#index'

  get 'mypage' => 'top#mypage'
  get 'bidded_items' => 'top#bidded_items'

  resources :sellers, only:[:index, :show] do
    get :coming, on: :member
    get :finished, on: :member
  end

  resources :tenders, only:[:index, :show] do
    resources :engines, only:[:show] do
      resources :bid_prices, only:[:new, :create, :edit, :update, :destroy]
    end
  end


  namespace :sellers, path:"organizer" do
    root 'top#index'
    resources :tenders do
      resources :engines
    end
    resource :tender_rule, only:[:show, :new, :create, :edit, :update]
    resources :tender_locations, only:[:new, :edit, :create, :update, :destroy]

    get 'account_info' => 'top#account_info'
    get 'new_seller_register_inquiry' => 'inquiry#new_seller_register_inquiry' # 販売企業入力画面
    post 'new_seller_register_inquiry_confirm' => 'inquiry#new_seller_register_inquiry_confirm' # 確認画面
    post 'new_seller_register_inquiry_thanks' => 'inquiry#new_seller_register_inquiry_thanks' # 送信完了画面
  end

  get 'corporate' => 'corporate#top'

end

end

end ###緊急避難

app/views/shared/_errors.html.erb
<% if obj.errors.present? %>
<div class="container">
  <div class='alert alert-danger'>
    <ul>
      <% obj.errors.full_messages.each do |msg| %>
      <li><%= msg %></li>
      <% end %>
    </ul>
  </div>
</div>
<% end %>

app/views/shared/_footer.html.erb
<div class="container">
  <footer class="text-center text-secondary my-5 bold">
    &copy; <%= Date.today.year %>

    <%= link_to "HeyWorld Inc.", corporate_path, target:["_blank"] %>

    <% if false %>

    &nbsp;|&nbsp;
    follow us on
    <%= link_to "https://twitter.com/NoteCrime", target:["_blank"] do %>
    <i class="fab fa-twitter fa-x"></i>
    <% end %>

    <% end %>

  </footer>
</div>

app/views/shared/_header.html.erb
<header>
  <nav class="navbar navbar-expand-lg navbar-light bg-light" id="corporateNav">
    <%= link_to 'HeyWorld', :root, class: "navbar-brand", style:"color:gray;" %>
    <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>

    <div class="collapse navbar-collapse" id="navbarSupportedContent">
      <ul class="navbar-nav ml-auto">

        <% unless current_seller %>
        <li class="nav-item">
          <% if current_user %>
          <%= link_to mypage_path, class: 'btn btn-primary' do %>
          <%= current_user.first_name ? current_user.first_name : "Hi Buyer!" %> | Top Page
          <% end %>
          <% else %>
          <%= link_to :new_user_session, class: 'btn btn-primary' do %>
          Buyer | Sign In
          <% end %>
          <% end %>
        </li>
        <% end %>

        &nbsp;&nbsp;

        <li class="nav-item">
          <% if current_seller %>
            <%= link_to sellers_root_path, class: 'btn btn-success' do %>
            <%= current_seller.company_name %>様トップページ
            <% end %>
          <% end %>
          <% unless current_user || current_seller %>
            <%= link_to new_seller_session_path, class: 'btn btn-success' do %>
            販売企業様はこちら
            <% end %>
          <% end %>
      </ul>
    </div>
  </nav>

  <nav class="navbar navbar-expand navbar-light bg-dark">

    &nbsp;&nbsp;&nbsp;&nbsp;

    <div class="text-white btn-right">
      <% if I18n.locale.to_s == "en" %>
      <%= link_to('日本語', { :locale => 'ja' }, { class: "btn btn-sm btn-primary js-scroll-trigger" }) %>
      <% else %>
      <%= link_to('English', { :locale => 'en' }, { class: "btn btn-sm btn-primary js-scroll-trigger" }) %>
      <% end %>
    </div>
    &nbsp;&nbsp;&nbsp;&nbsp;
    &nbsp;&nbsp;&nbsp;&nbsp;

    <ul class="navbar-nav align-items-center">
      <i class="far fa-user-circle fa-2x py-2 text-white"></i>
      <span class="px-2 text-white">welcome!</span>
      <li class="nav-item dropdown">
        <a class="text-white dropdown-toggle" href="#" id="navbarDropdownMenuLink" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
          <% if current_seller %>
          <%= current_seller.company_name %>様
          <% elsif current_user %>
          <strong><%= current_user.first_name %></strong>
          <% end %>
        </a>
        <div class="dropdown-menu" aria-labelledby="navbarDropdownMenuLink">
          <% if current_seller %>
            <%= link_to sellers_root_path, class:"dropdown-item" do %>
            <%= current_seller.company_name %>様トップページ
            <% end %>
          <% elsif current_user %>
            <%= link_to mypage_path, class:"dropdown-item" do %>
            <i class="fas fa-home"></i>
            My Page
            <% end %>
          <% else %>
            <%= link_to new_user_session_path, class:"dropdown-item" do %>
            Buyer Sign In
            <% end %>
          <% end %>

          <% if current_user %>
            <div class="dropdown-divider"></div>
            <%= link_to bidded_items_path, class: 'dropdown-item' do %>
            <i class="fas fa-list-ol"></i>
            Bidded Items
            <% end %>
          <% end %>

          <div class="dropdown-divider"></div>
          <% if current_seller %>
            <%= link_to destroy_seller_session_path, method: :delete, class: 'dropdown-item' do %>
            <i class="fas fa-sign-out-alt"></i>
            ログアウト
            <% end %>
          <% elsif current_user %>
            <%= link_to destroy_user_session_path, method: :delete, class: 'dropdown-item' do %>
            <i class="fas fa-sign-out-alt"></i>
            Sign Out
            <% end %>
          <% else %>
          <%= link_to new_seller_session_path, class:"dropdown-item" do %>
          販売企業様サインイン
          <% end %>
          <% end %>
        </div>
      </li>
    </ul>

  </nav>

</header>